### ISSUE TITLE
【需求】绘制接触力链图

### ISSUE THREAD

**Issue by geovbox** [geovbox/vbox_doc#2]
### vbox2jpg 添加参数
  `--plotcforce=<bool>` 
绘制接触力链图，`<bool>` 取值 `true/false` ，默认 `true`

### 实现思路
在颗粒变形图中加入子图，竖向排列，颗粒变形图为第一行子图1，接触力链图为第二行子图2。
接触力链图中:

-  蓝色: 表示bond压缩
-  红色: 表示bond拉伸
-  黑色: 表示contact接触，呈压缩状态。

![cforce](https://user-images.githubusercontent.com/46532304/86761334-77fe8980-c078-11ea-8475-c22f1fe229d0.png)

### 实例

- `vbox2jpg --dir=./data --plotcforce=true`

**Comment by Ivyxwq** [comment]
### ###  新增绘制黏结力链图 `--bondplot=true`
在vbox2jpg新增的黏结力链绘图功能--bondplot 默认`false`。
当 `--bondplot=true`，根据.dat绘制黏结力链图，黑色为没有黏结的接触状态（contact），蓝色为有黏结的挤压状态（bond_push），红色为有黏结的拉伸状态(bond_pull)，黏结和接触的关系请参照李长圣的博士论文。
同时在dir指定的文件夹中输出contactbond_num.txt，计算出.dat文件中的接触黏结数量。
以ex1_push为例，黏结参数采用T4，挤压每5000步输出.dat文件，绘图语句 `vbox2jpg --dir=./data --bondplot=true`  构造形变图，黏结力链图以及不同时刻的新断裂的黏结力链数如如图所示，26000步-31000步形成断层F1活动，415对黏结力链断开，36000步-41000步断层F2活动，219对黏结力链断开。
![image](https://user-images.githubusercontent.com/48645980/88884509-5a80a200-d269-11ea-820c-b993db31eac5.png)
