### ISSUE TITLE
[bug] del restore gen混合使用时，不同时间步的颗粒id重复，导致应变计算错误。

### ISSUE THREAD

**Issue by geovbox** [geovbox/vbox_doc#3]
del restore gen混合使用时，不同时间步的颗粒id重复，导致应变计算错误。
### 例如
1. del id=5的颗粒
2. restore gen，会新生成一个 id=5的颗粒，该颗粒与步骤1中的颗粒不是同一个颗粒
3. 应变计算会寻找同一id号的颗粒，以上del restore gen方法，导致颗粒识别错误，应变计算会错误。

### 当前解决方法
1. del id=5的颗粒
2. restore gen，此时引入idmin，即gen idmin 10。此时，新生成的颗粒起始id为10，与上一步删除的id=5的颗粒不会重复。
3. 应变计算基于id号寻找不同时间中的颗粒，不会出现同id号，而不是同一颗粒的问题，应变计算正确。

### 颗粒在时间线上不唯一
* 前提：颗粒唯一性仅仅通过id号识别。

这个问题本质是颗粒id在整个时间线上不唯一，不同时间两个名字一样的两个人，同时出现在应变计算系统中，导致应变计算错误。尽管颗粒id=5被删除，不存在了。以后的时间中，id=5则永远不能被启用，以免打破颗粒在整个时间线上的唯一性。

### 后续版本修复方法
.sav文件中保存一个idmax，以后restore gen的时候，从这个idmax生成颗粒，可以保证id号的在整个时间线上的唯一性。

**Comment by demsheng** [comment]
2.0以上版本已经修复此bug

**Comment by geovbox** [comment]
2.0以上版本已经修复此bug
