### ISSUE TITLE
[bug]vboxdaily -j 24 ex.py中-j 24省略，程序无法运行，显示段错误。

### ISSUE THREAD

**Issue by demsheng** [geovbox/vbox_doc#4]
`vboxdaily -j 24 ex.py` 中 `-j 24` 省略，程序无法运行，显示段错误。

### bug细节

环境：南京大学高性能计算中心

`vboxdaily ex.py`

`ex.py` 中内容如下：
```
res 1.sav
```

**Comment by geovbox** [comment]
已修复。
原因： 没定义环境变量`OMP_NUM_THREADS`,  `vboxdaily push.py` 时，无法获取线程数。
修复后： 如果不定以定义环境变量 `OMP_NUM_THREADS` ， `vboxdaily ex.py` 时，线程数设置为CPU的核心数。
